language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"

cache: pip

services:
    - redis-server

install:
    - pip install .

script:
    - pushd test
    - managment.py -p etc/pipeline.conf -r etc/runtime.conf -s etc/startup.conf &
    - MGMT=$!
    - ./generator.py
    - sleep 120
    - kill -9 $MGMT
    - popd
