language: python

python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "nightly"

cache: pip

services:
    - redis-server

install:
    - pip install .

script:
    - pushd test
    - launch_queues.py -p etc/pipeline.conf -r etc/runtime.conf &
    - Q_PID=$!
    - launch_modules.py -r etc/runtime.conf -s etc/startup.conf &
    - M_PID=$!
    - ./generator.py
    - sleep 120
    - kill -9 $Q_PID
    - kill -9 $M_PID
    - popd
